#!/bin/sh
#
# Executes an optional project shell scripts at specific steps of
# the build process
#
# usage: run-docker-build-hook <hook_name>
#
# it will check /app/.docker-build-hooks/<hook_name>* and if any
# are found (sorted by name) they will be executed in turn
#

set -e

hooks_dir=".docker-build-hooks"
hook_name="$1"

if [ -z "$hook_name" ] ; then
  echo "FATAL: run_hooks.sh required a hook_name as first parameter"
  exit 1
fi
shift

for file in `ls -1 $hooks_dir | egrep "^$hook_name"` ; do
  if [ -x "$hooks_dir/$file" ] ; then
    "$hooks_dir/$file"
  fi
done
